### ISSUE TITLE
Usage with TabBarView and ListView children

### ISSUE THREAD

**Issue by emvaized** [bnxm/sliding_sheet#39]
Hi!
I want to use SlidingSheet widget with `TabBarView` widget, and two `GridView` pages.
When I try to pass it to `builder`, I get an error "Horizontal viewport was given unbounded height."

I tried wrapping TabBarView with a `Container` with fixed height and width, but then my pages' content is clipped by this height.

How to deal with such a scenarios? Thanks!

**Comment by emvaized** [comment]
I've replaced `TabBarView` with `PageView`, and set `shrinkWrap = true` for each page, and now issue is gone.

**Comment by bnxm** [comment]
Well, you have to impose a fixed height on the `TabBarView` cause it will try to expand to infinity. I think why your content might be clipped is because you have to vertical scroll views inside of each other and so the `SlidingSheet` is intercepting all the gesture events before they can get to the `GridView`.

**Comment by emvaized** [comment]
> Well, you have to impose a fixed height on the `TabBarView` cause it will try to expand to infinity. I think why your content might be clipped is because you have two vertical scroll views inside of each other and so the `SlidingSheet` is intercepting all the gesture events before they can get to the `GridView`.

Sure! That's the widget structure I have: 
`TabBarView` -> `SingleChildScrollView` -> `GridView`

Is it possible to make it work somehow?

**Comment by emvaized** [comment]
@bnxm 
I've made pull request some time ago which provided `CustomScrollbarBuilder` property - it somehow allowed me to set `PageView` as a child, but with some issues...
