### ISSUE TITLE
Unexpected behavior happens during opening the sliding sheet

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [bnxm/sliding_sheet#43]
Hi @bnxm Welcome again
I have here that example
```
showSlidingBottomSheet(
      context,
      builder: (ctx) => SlidingSheetDialog(
        duration: Duration(milliseconds: 250),
        snapSpec: SnapSpec(snappings: [1]),
        builder: (ctx, state) => Material(
          child: Column(
            children: <Widget>[
              TextFieldTest (),
              TextFieldTest (),
              TextFieldTest (),
              TextFieldTest (),
              TextFieldTest (),
              TextFieldTest (),
            ],
          ),
        ),
      ),
    );
```
```
class TextFieldTest extends StatefulWidget {
  @override
  _TextFieldTestState createState() => _TextFieldTestState();
}

class _TextFieldTestState extends State<TextFieldTest> {
  initState() {
    // Future(() => controller.text = 'asdsfsds');
    super.initState();
  }

  final controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return TextField(controller: controller);
  }
}

```

Till now you will find every thing works well.
But just try to remove the comment from this line
```// Future(() => controller.text = 'asdsfsds');``` then notice the results, You will find a completely unexpected behavior

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/52201392/84954315-74b95300-b0f5-11ea-91d7-8415033097ff.gif)

That strange behavior disappears when waiting for the panel to become completely open, then update the controller text. So if you replaced the `Future` with
```Future.delayed(Duration(mileseconds: 350),() => controller.text = 'asdsfsds');``` no thing strange will happen.
But the problem here that when updating the controller text during opening the panel and before it becomes completely open, So help please master @bnxm

**Comment by AlaaEldeenYsr** [comment]
Here is another issue which is some how related to the one in the first comment,
```
    showSlidingBottomSheet(
      context,
      builder: (ctx) => SlidingSheetDialog(
        duration: Duration(milliseconds: 350),
        snapSpec: SnapSpec(snappings: [1]),
        builder: (ctx, state) => Material(
          color: HexColor('171717'),
          child: ContainerTest(),
        ),
      ),
    );
```
```
class ContainerTest extends StatefulWidget {
  @override
  _ContainerTestState createState() => _ContainerTestState();
}

class _ContainerTestState extends State<ContainerTest> {
  initState() {
    Future(() => setState(() => height = 500));
    super.initState();
  }

  var height = 200.0;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: height,
      color: Colors.blue,
      alignment: Alignment.center,
      child: Text('$height'),
    );
  }
}
```
During opening the panel and before it becomes completely open, I did setState to change the height of the container from 200 to 500, Good that happened during the panel opening, Looks like that the panel in that case doesn't listen to the sizes changes of its body, Because after the panel get completely opened you will see the panel height is 200 not 500

**Comment by bnxm** [comment]
Could you again switch to the dev branch and see if it works now?

~~~yaml
sliding_sheet:
    git: 
      url: https://github.com/bnxm/sliding-sheet
      ref: dev
~~~

For some reason the `NotificationListener` doesn't notify the sheet about the size changes of the children during the first frames. Now the sheet should check after the initial flyin whether the content size changed and adjust accordingly.

**Comment by AlaaEldeenYsr** [comment]
@bnxm , Alright the first issue in the first comment https://github.com/bnxm/sliding-sheet/issues/43#issue-640770394 was the important one and it's solved well Thank you.
And about the issue in the second comment https://github.com/bnxm/sliding-sheet/issues/43#issuecomment-645655881 it's solved also but the size changes get reflected to the panel after the first flyin as you mentioned here https://github.com/bnxm/sliding-sheet/issues/43#issuecomment-647004592, Actually i don't see any problem in that, It's working.
really thank you master @bnxm , See you next issue

**Comment by AlaaEldeenYsr** [comment]
Hi @bnxm, Looks like our issue still there. But now it's harded to reproduce as it's not stable, Some times works well but other times as you see in the Gif.

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/52201392/86963877-837bae80-c165-11ea-8719-d4d8c2320f72.gif)

What's happening that i (async) fetch some data just after the panel gets completely open. then display the results in the panel body, The panel should listen for the body size changes and moves up to the max point dynamically. but as you see in the gif it's not !!

Same issue existed whether i fetch the data and display it after the panel gets completely open. Or during the panel oppening and before it becomes completely open. Please help @bnxm
