### ISSUE TITLE
How to hide background mask? [HELP WANTED]

### ISSUE THREAD

**Issue by Dhuliang** [bnxm/sliding_sheet#47]
I use `showSlidingBottomSheet` to show drag sheet , half height of `MeidaQuery.of(Context).size.height`.
And I want to click header area , how can I hide mask so that I trigger gesture event?

**Comment by michinchin** [comment]
use `SlidingSheet` as the parent and show the sheet rather than calling showSlidingBottomSheet` and set `closeOnBackdropTap` to false

**Comment by bnxm** [comment]
I'm not sure what you mean... Isn't the point of showing a `dialog` exactly not to trigger a gesture event when tapped outside the dialog area? Or what do you mean with 'header area'?
