### ISSUE TITLE
Fullscreen for Smaller Body

### ISSUE THREAD

**Issue by oberprah** [bnxm/sliding_sheet#61]
I would like to have a fully expanded sheet even, when the body does not need the whole space. I've set therefore the `minHeight`.

```dart
import 'package:flutter/material.dart';
import 'package:sliding_sheet/sliding_sheet.dart';

const HEADER_HEIGHT = 56.0;

void showAsBottomSheet(BuildContext context) async {
  await showSlidingBottomSheet(context, builder: (context) {
    return SlidingSheetDialog(
      avoidStatusBar: true,
      elevation: 8,
      cornerRadius: 16,
      cornerRadiusOnFullscreen: 0,
      liftOnScrollHeaderElevation: 12.0,
      liftOnScrollFooterElevation: 12.0,
      minHeight: MediaQuery.of(context).size.height -
          MediaQuery.of(context).padding.top -
          MediaQuery.of(context).padding.bottom,
      snapSpec: const SnapSpec(
        snap: true,
        snappings: [1.0],
        positioning: SnapPositioning.relativeToAvailableSpace,
      ),
      builder: (context, state) {
        return Container(
          // height: 1300,
          child: Center(
            child: Material(
              child: InkWell(
                onTap: () => Navigator.pop(context, 'This is the result.'),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Text('This is the content of the sheet'),
                ),
              ),
            ),
          ),
        );
      },
      headerBuilder: (context, state) {
        return Container(
          height: HEADER_HEIGHT,
          width: double.infinity,
          // color: getCurrentTheme().dialogBackgroundColor,
          alignment: Alignment.center,
          child: Text(
            'This is the header',
            style: Theme.of(context)
                .textTheme
                .bodyText1
                .copyWith(color: Colors.white),
          ),
        );
      },
    );
  });
}
```
Unfortunately for the code above the body is still scrollable (shadow in the image below).

![image](https://user-images.githubusercontent.com/33762726/101683212-f23a9c00-3a64-11eb-82d0-1a25dc5fd1e3.png)

If I reduce the `minHeight`, the body is not scrollable anymore, but the sheet does not fill the whole screen.

![image](https://user-images.githubusercontent.com/33762726/101683290-0bdbe380-3a65-11eb-9699-584c0cdb26f2.png)

**Comment by bnxm** [comment]
I think you'll also have to deduct the height of the header, as the minHeight is only applied to the scrollable child.

**Comment by oberprah** [comment]
@bnxm this is exactly, what I've done in the second picture. Unfortunately, I did not mention this clearly in the issue description.

I've two cases:
1. The `minHeight` is `availableSpace - heightOfHeader`: the body is not scollabe, but the card is not in fullscreen (round corner)
2. For all heights larger the height in 1.: the card is in fullscreen, but the body is scollable
