### ISSUE TITLE
Space between header and body of bottomSheet

### ISSUE THREAD

**Issue by ahmaddarwesh** [bnxm/sliding_sheet#63]
How to remove space between **header** and **body** 

<img src="https://user-images.githubusercontent.com/25372065/104106452-ac206480-52be-11eb-9fa8-49c69c3f58b6.png" width="250" height="500">

**Comment by spreakfark** [comment]
Had the same problem. This happens with ListView, because it has a default top padding. You have to override the padding to remove it.
```dart
ListView.builder(
    padding: EdgeInsets.zero, // <- add this
    shrinkWrap: true,
    physics: const NeverScrollableScrollPhysics(),
    ...
)
```
