### ISSUE TITLE
[showSlidingBottomSheet] parentBuilder not called

### ISSUE THREAD

**Issue by Supercaly** [bnxm/sliding_sheet#70]
I was trying to display a modal bottom sheet using `showSlidingBottomSheet`, but my inner widget is a little complex because it uses a bloc and this bloc should be reachable event by the header widget. Looking inside the source code i found the `parentBuilder` parameter so I tried using it:

```dart
 showSlidingBottomSheet(
    context,
    resizeToAvoidBottomInset: false,
    parentBuilder: (context, sheet) => BlocProvider<LabelsBloc>(
      create: (context) => LabelsBloc(
        initialValue: labels,
        repository: locator<LabelRepository>(),
      )..fetch(),
      child: sheet,
    ),
    builder: (context) => SlidingSheetDialog(
      cornerRadius: 16.0,
      headerBuilder: (context, state) => // Use the bloc
      builder: (context, sheetState) {
        return BlocBuilder<LabelsBloc, LabelsState>(
          builder: (context, state) {
            // Use the bloc
          },
        );
      },
    ),
  );
```

This code works correctly only because I set `resizeToAvoidBottomInset` to `false`.

Looking in the source code I found this part:

```dart
if (resizeToAvoidBottomInset) {
  return Padding(
    padding: EdgeInsets.only(
      bottom: MediaQuery.of(context).viewInsets.bottom),
      child: sheet,
    );
}

if (parentBuilder != null) {
  return parentBuilder(context, sheet);
}

return sheet;
```

so the `parentBuilder` is built only if the `resizeToAvoidBottomInset` is false.

Now I don't think this is something wanted by the library since in the documentation it's stated that `parentBuilder` could be used to provide a `Theme`, so it's reasonable to think that a user would need a Theme and avoid a bottom inset.
Adding on this, since `resizeToAvoidBottomInset` is `true` by default if a user sets only the `parentBuilder` it won't be displayed and the user won't know why.

**Comment by bnxm** [comment]
Thanks, that was indeed not intended.
