### ISSUE TITLE
[Question] Is it possible to have two stacked sliding sheets in one view whose behavior is connected?

### ISSUE THREAD

**Issue by lane-faison** [bnxm/sliding_sheet#71]
Hoping to find a way to have two sliding sheets stacked together, and scrolling on one sheet can affect the behavior of the other. Basic widget tree setup would look something like this:
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade200,
      appBar: AppBar(
        title: Text('Sliding Sheets Example'),
      ),
      body: Stack(
        children: <Widget>[
          FirstSlidingSheet(),
          SecondSlidingSheet(),
        ],
      ),
    );
  }
```
The behavior I am hoping for is that sliding up on the `SecondSlidingSheet`, which would appear on top of the `FirstSlidingSheet`, would cause the `FirstSlidingSheet` to slide up as well. Similar behavior for when sliding down on a sheet. TIA!

**Comment by bnxm** [comment]
No, this is quite a custom behavior and not supported. However, you may be able, using the listener and onSnap callbacks along with two controllers for each sheet, to create that kind of behavior. So for instance, when `SheetA` snapped to position `x` you can animate `SheetB` to position `y` if that is what you are looking for.
