### ISSUE TITLE
BackdropInteractable is not working at SnapSpec.headerSnap

### ISSUE THREAD

**Issue by sahanshah-k** [bnxm/sliding_sheet#73]
Back drop interaction is working everywhere till it reaches the headersnap, and stops working after that. After some work around I got into this, this is working for me. Not sure if this is the right way.
          snappings: [
              SnapSpec.headerSnap,
              SnapSpec.headerSnap,
              midSnap,
              SnapSpec.expanded,
            ],
            
Please take a look. 
Thanks

**Comment by bnxm** [comment]
`isBackdropInteractable` can be used to customize the backdrop interaction behavior.
