### ISSUE TITLE
Snap to height of child if < maxExtent?

### ISSUE THREAD

**Issue by sabetAI** [bnxm/sliding_sheet#79]
Is there a way to constrain the sliding sheet to expand up until the height of the child, if it's less than the maxExtent? I want to avoid redundant empty space padding the content.

**Comment by sabetAI** [comment]
This is the issue I'm hoping to fix with your package https://github.com/flutter/flutter/issues/41599.

**Comment by bnxm** [comment]
Yes, but the sheet is already doing this by default. Otherwise you'll have to provide some sample code if it is not working for you.
