### ISSUE TITLE
Calling expand or collapse does not update state

### ISSUE THREAD

**Issue by mees-brenzie** [bnxm/sliding_sheet#80]
Hi! 

I have been trying to use the header as a large button top open and close the sliding panel. Unfortunately, after calling expand() or collapse() on the controller, it does not update the state. Meaning that checking the state.isCollapsed keeps returning true, even though the sliding panel has already expanded. See the code example. Not sure if I'm doing something wrong, but I'd love to hear your opinion on this!

Thanks!

```
SlidingSheet(
  controller: sheetController,
  duration: kTransitionDuration,
  elevation: 8,
  cornerRadius: 16,
  closeOnBackButtonPressed: true,
  closeOnBackdropTap: true,
  backdropColor: Colors.black38,
  snapSpec: SnapSpec(
      snap: true,
      snappings: [80, 400],
      positioning: SnapPositioning.pixelOffset),
  headerBuilder: (context, state) {
      return Container(
          height: 80,
          width: double.infinity,
          color: config.secondaryColor,
              child: TextButton(
                  style: TextButton.styleFrom(primary: Colors.white),
                  child: Text('test'),
                  onPressed: () {
                      if (state.isCollapsed) {
                        sheetController.expand();
                      } else {
                        sheetController.collapse();
                      }
                  },
               ),
         );
   },
   builder: (context, state) {
       return Container(
           height: 200,
           color: Colors.white,
       );
   },
   body: ...
);  
```

**Comment by bnxm** [comment]
It's because you're checking `state.isExpanded` outside the build method and therefore the state may no longer represent the state of the sheet when the button is pressed. 

You can use the `state` field on the `SheetController` to always get the most recent state object or use `SheetListenerBuilder` if you need to continously react to state changes (for instance when implementing transition effects).

**Comment by mees-brenzie** [comment]
Thank you! Changing the onPressed function to

```
onPressed: () {
  if (sheetController.state.isCollapsed) {
    sheetController.expand();
    } else {
      sheetController.collapse();
    }
}
```

did the trick!
