### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by naamapps** [bnxm/sliding_sheet#86]
Hey,
I have some performance issues with the sliding sheet,
the scrolling and overall fluidity is lacking.
When comparing this package with others (especially - https://github.com/akshathjain/sliding_up_panel), there is a big difference in performance. 

I know this package have a lot of great features and the logic behind it is complex and have plenty of calculations happening in the background but it's hitting the performance unfortunately.
The great wide range of features is why I'm using this package instead of others but it costs a lot of performance. 

For example with a Galaxy S21 Ultra, with a **dynamic** (comments section) list of 50 items, I get 30-40 fps, it gets really laggy, which is very concerning because this phone is fast and top tier.
I wonder how it performs with a low end device - I can guess a little worse.

When inserting new items or removing there will be lags. 
The worst thing to do is to insert items in the middle of the list. 

Is there optimization that can be done? 

I hope you will see this issue, this is a really important one!
Thanks

**Comment by bnxm** [comment]
You might wanna try the `customBuilder` in version `0.5.1-dev+1` instead of the normal `builder` where you can supply your own `ListView` without having to `shrinkWrap` it. You have to supply the `ScrollController` in the builder to the `ListView` for it to work. In theory this should give better performance for long lists. Haven't tried yet though.

**Comment by naamapps** [comment]
@bnxm Thank you so much for the quick reply and support!
I'll try it right away

**Comment by naamapps** [comment]
@bnxm Did you publish it to pub.dev? I don't see an update yet

**Comment by bnxm** [comment]
Yes its a prerelease

**Comment by naamapps** [comment]
@bnxm Maybe I missed something but the sheet doesn't scroll at all now, and not reacting to flinging (need to drag the header all the way for it to extend).
I put the scroll controller in the list view and set shrink wrap to false.
Tries also to sest physics to never scroll and always scroll.
When putting always scroll, the list scrolls but the sheet doesn't collapse when swiping down at the top of the list.

**Comment by naamapps** [comment]
Forgot to mention, the performance is much better!
Just need to iron out those bugs and the package is perfect :)

**Comment by naamapps** [comment]
Also getting this when leaving the page.
I guess it's because you use the scroll controller after the page is already disposed somewhere.
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 108 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.`

**Comment by bnxm** [comment]
Please show me the code of the `customBuilder` method

**Comment by naamapps** [comment]
Sorry @bnxm, all good now it was my mistake.
Just a little problem, since my sheet is dynamic, sometimes there aren't any listviews inside, so the exception I wrote earlier was because of this.
A listview must exist in the widget tree for it to work?
Maybe worth adding a bool wrapCustomBuilderWithListView, which can dynamically be changed for scenarios where we don't have listview inside the custom builder.

Other than that it really work well, well done sir!
Could you please remove all the logging you added too?
Thanks again :)

**Comment by bnxm** [comment]
> A listview must exist in the widget tree for it to work?

Yes, the `ScrollController` contains the logic.

> Maybe worth adding a bool wrapCustomBuilderWithListView, which can dynamically be changed for scenarios where we don't have listview inside the custom builder.

The normal `builder` does that. Otherwise, just wrap your child inside a `SingleChildScrollView`.

**Comment by naamapps** [comment]
Cool got it.
Thanks, working perfectly!

**Comment by markbulingit** [comment]
Can you all please make a decent readable code for the solutions, you are all being selfish.
