### ISSUE TITLE
Bug with Usage as a Widget

### ISSUE THREAD

**Issue by nakshatrasinghh** [bnxm/sliding_sheet#88]
<img width="737" alt="Screenshot 2021-09-04 at 7 23 14 PM" src="https://user-images.githubusercontent.com/53419293/132096805-2a598d1e-42bc-4ae8-b011-cc389402ed7a.png">

I'm using an iOS simulator, I copied the entire @override method from the example, it doesn't seem to work. Any help?

<img width="1440" alt="Screenshot 2021-09-04 at 7 24 07 PM" src="https://user-images.githubusercontent.com/53419293/132096837-f1d6c9ab-712f-4c52-8288-5ed560170ebd.png">

**Comment by bnxm** [comment]
Well, the error mentions that you are missing the `MaterialApp` (or `CuptertinoApp`) which is the basis for all flutter apps. This has nothing to do with this package though.
