### ISSUE TITLE
passing data to header

### ISSUE THREAD

**Issue by brainunknown** [bnxm/sliding_sheet#92]
Hi! First of all thanks for this amazing plugin! I hope some day I will be able to do things like this. Anyway..
How to pass data (userName) to the header?

I am testing the example provided, and trying to pass data to the buildHeader Widget. Like this:

```
`// Sliding Sheet widget
  Widget buildSheet() {
    return SlidingSheet(
    ...
    body: buildMap(),
       headerBuilder: buildHeader(userName: users.userName),
       builder: buildChild,

    );
  }`
```

```
`Widget buildHeader({BuildContext context, SheetState state, String userName}) {
    return CustomContainer(....`
```

But I am getting the error:

> Error: The argument type 'Widget' can't be assigned to the parameter type 'Widget Function(BuildContext, SheetState)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/flutter_sdk/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/flutter_sdk/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'SheetState' is from 'package:sliding_sheet/src/sheet.dart' ('/C:/flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sliding_sheet-0.4.1/lib/src/sheet.dart').

Thanks for your time,
Ricardo

**Comment by bnxm** [comment]
You are trying to assign a widget to a function parameter. `headerBuilder: buildHeader(userName: users.userName)` has to be like this: `headerBuilder: (context, state) => buildHeader(context: context, state: state, userName: users.userName)`

**Comment by brainunknown** [comment]
Now I understand. Learning Everyday :)

Thanks @bnxm
