### ISSUE TITLE
Use ScrollTo() to scroll anywhere

### ISSUE THREAD

**Issue by huangkaichang** [bnxm/sliding_sheet#94]
Hi,

I was trying to control the Sliding Sheet height with ScrollTo() function, but I cannot control it to any offset I want, so I just modified the sample project.

I modified the "Show Map" button click event to this:
```dart
return button(
                Icon(
                  !isExpanded ? Icons.list : Icons.map,
                  color: mapsBlue,
                ),
                Text(
                  !isExpanded ? 'Steps & more' : 'Show map',
                  style: textStyle.copyWith(
                    fontSize: 15,
                  ),
                ),
                !isExpanded
                    ? () => controller.scrollTo(0.6) // Modified here, click to scroll to 0.6 instead of maxExtent
                    : controller.collapse,
                color: Colors.white,
                border: BorderSide(
                  color: Colors.grey.shade400,
                  width: 2,
                ),
              );
```

But the sliding sheet still scroll to the maxExtent. I did't change anything else in Sample Code

Could you tell me where I am missing?

**Comment by bnxm** [comment]
ScrollTo will always expand the sheet. snapToExtent might be the function you are looking for.

**Comment by huangkaichang** [comment]
@bnxm Thanks! snapToExtent() is the one I'm looking for. Closing the issue
